export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const LOAD_TAGS_SUCCESS = "LOAD_TAGS_SUCCESS";
export const LOAD_ARTICLES_SUCCESS = "LOAD_ARTICLES_SUCCESS";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const DELETE_ARTICLES_SUCCESS = "DELETE_ARTICLES_SUCCESS";
export const LOAD_SELECTED_ARTICLE_SUCCESS = "LOAD_SELECTED_ARTICLE_SUCCESS";
export const MANAGE_ARTICLE_SUCCESS = "MANAGE_ARTICLE_SUCCESS";
export const LOAD_COMMENTS_SUCCESS = "LOAD_COMMENTS_SUCCESS";
export const SAVE_COMMENT_SUCCESS = "SAVE_COMMENT_SUCCESS";
export const DELETE_COMMENT_OPTIMISE = "DELETE_COMMENT_OPTIMISE";
export const MARK_ARTICLE_FAV_OPTIMISE = "MARK_ARTICLE_FAV_OPTIMISE";
export const MARK_ARTICLE_UN_FAV_OPTIMISE = "MARK_ARTICLE_UN_FAV_OPTIMISE";

export const BEGIN_FAV_API_CALL = "BEGIN_FAV_API_CALL";
export const END_FAV_API_CALL = "END_FAV_API_CALL";

export const LOAD_SPECIAL_ARTICLES_SUCCESS = "LOAD_SPECIAL_ARTICLES_SUCCESS";
export const DELETE_SPECIAL_ARTICLES_SUCCESS =
  "DELETE_SPECIAL_ARTICLES_SUCCESS";
export const MARK_MY_ARTICLE_UN_FAV_OPTIMISE =
  "MARK_MY_ARTICLE_UN_FAV_OPTIMISE";
export const MARK_SPECIAL_ARTICLE_FAV_OPTIMISE =
  "MARK_SPECIAL_ARTICLE_FAV_OPTIMISE";
export const MARK_SPECIAL_ARTICLE_UN_FAV_OPTIMISE =
  "MARK_SPECIAL_ARTICLE_UN_FAV_OPTIMISE";
export const MARK_SELECTED_ARTICLE_FAV_OPTIMISE =
  "MARK_SELECTED_ARTICLE_FAV_OPTIMISE";
export const MARK_SELECTED_ARTICLE_UN_FAV_OPTIMISE =
  "MARK_SELECTED_ARTICLE_UN_FAV_OPTIMISE";
// export const LOAD_USER_DETAILS_SUCCESS = "LOAD_USER_DETAILS_SUCCESS";
